function [bin_final] = hamming_decode(bin_received)
% hamming_decode() Decodes and corrects a received hamming code
%   See also: hamming_encode()
% INPUTS
%   bin_received - Hamming code that was generated by hamming_encode()
% OUTPUTS
%   bin_final - Corrected copy of bin_received

nbp = hamming_nbp(length(bin_received), true);

% Detect errors
vect_error = error_check(bin_received,nbp);
if sum(vect_error) ~= 0
    % Error exists, so find it and correct it
    bin_corrected = correct_message(bin_received,nbp);
    bin_final = message_decode(bin_corrected,nbp);
else
    % No error; simply decode the message
    bin_final = message_decode(bin_received, nbp);
end

end